### ISSUE TITLE
Add support for "main" branch

### ISSUE THREAD

**Issue by kulla** [splish/changelog#22] opened 2021-08-30 09:41 UTC
After changing https://github.com/serlo/api.serlo.org to `main` branch I get the following error when I call `/scripts/changelog` after we changed `master` to `main`:

```
[Error: no reference found for shorthand 'master'] {
  errno: -3,
  errorFunction: 'Reference.dwim'
}
```

BTW: Executing the script cleared `CHANGELOG.md` so I guess there is a handling of an error missing. :-)

**Comment by inyono** [comment] 2021-08-30 19:55
Duplicate of #13.

**Closed as completed by inyono** 2021-08-30 19:55 UTC
